### ISSUE TITLE
The processor architecture of the project being built "Any CPU" is not supported

### ISSUE THREAD

**Issue by BrunoVT1992** [oysteinkrog/SQLite.Net-PCL#107]
I am using Xamarin forms 1.3 with Windows Phone 8 but I get this error:

Error	2	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "SQLite.WP80, Version=3.8.7.4". Please consider changing the targeted processor architecture of your project (in visual studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, ARM"

**Comment by oysteinkrog** [comment]
Are you using the wp8 platform nuget in your application, or are you trying to compile this solution?

**Comment by BrunoVT1992** [comment]
<packages>
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="wp80" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="wp80" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="wp80" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="wp80" />
  <package id="SQLite.Net.Platform.WindowsPhone8" version="2.5" targetFramework="wp80" />
  <package id="SQLite.Net-PCL" version="2.5" targetFramework="wp80" />
  <package id="sqlite-net-wp8" version="3.8.5" targetFramework="wp80" />
  <package id="WPtoolkit" version="4.2013.08.16" targetFramework="wp80" />
  <package id="Xamarin.Forms" version="1.3.1.6296" targetFramework="wp80" />
  <package id="Xamarin.Forms.Maps" version="1.3.1.6296" targetFramework="wp80" />
  <package id="Xamarin.Insights" version="1.8.2.105" targetFramework="wp80" />
</packages>
