### ISSUE TITLE
Excpetion when 'await Task.WhenAll()' is used

### ISSUE THREAD

**Issue by Devfingers** [oysteinkrog/SQLite.Net-PCL#108]
I use emulator in Visual Studio 2013, solution Windows Phone 8. 

When I use 'await Task.WhenAll()' to create my tables I get a sqlite exception: "Busy". If I call directly 'await _connection.CreateTable[s]Async<>()' an exception doesn't occur. Can you check this code below?

The other thing is that I do some async CRUD operations for a while after run my application and if I deactivate and activate it during these operations I get exception 'Database is locked'. Is it something because any sqlite resource is not disposed/closed when application goes into the deactivated state?

    public class SQLiteDataService : IDataService
    {
        private ISQLitePlatform _sqlitePlatform;
        private IStorageService _storageService;
        private SQLiteAsyncConnection _connection;
        private static readonly string DB_FILE_NAME = "database.db";
    
        public SQLiteDataService(ISQLitePlatform sqlitePlatform, IStorageService storageService)
        {
            _sqlitePlatform = sqlitePlatform;
            _storageService = storageService;
            InitializeAsync();
        }        

        private async Task InitializeAsync()
        {    
            if (_connection == null)
            {
                string databaseFile = await _storageService.GetPathForFileAsync(DB_FILE_NAME);
                _connection = new SQLiteAsyncConnection(() => new SQLiteConnectionWithLock(_sqlitePlatform, new SQLiteConnectionString(databaseFile, false)));
    
                await Task.WhenAll(new Task[] 
                   _connection.CreateTableAsync<Table1>(),
                   _connection.CreateTableAsync<Table2>(),
                   _connection.CreateTableAsync<Table3>(),
                   _connection.CreateTableAsync<Table4>(),
                   _connection.CreateTableAsync<Table5>(),
                   _connection.CreateTableAsync<Table6>(),
                });
             }
        }
    }

**Comment by oysteinkrog** [comment]
One error I noticed is that you call InitializeAsync from the constructor, calling async methods from a constructor is not good.
What happens if you call (and await) InitializeAsync outside the constructor?
If you want the initialization to happen synchronously in the constructor, just call CreateTable directly on the connection, without using an async connection.

**Comment by Devfingers** [comment]
I've tried your suggestion so have removed InitializeAsync from the constructor and call this function explicity when my object is created and I get the same exception. The error is gone only when I don't use Task.WhenAll.

**Comment by Devfingers** [comment]
I've investigated this issue again and it seems VS emulator doesn't dispose/close a process/task which block access to a database file and then an exception is thrown ("Busy" or "Database is locked"). My scenario is as follows:
1. Run application using emulator
2. Async CRUD operations are performed, it takes up to 1 min.
3. Close emulator during operations from point 2.
4. Run application again
5. Exception is thrown

**Comment by oysteinkrog** [comment]
This does not sound like a problem with sqlite.net.
