### ISSUE TITLE
Bulk Statements and Transactions

### ISSUE THREAD

**Issue by shawnburge** [oysteinkrog/SQLite.Net-PCL#109]
Would it be possible to add functionality to handle Bulk inserts/deletes/updates or Begin/Commit transactions?

Thanks!!
Shawn

**Comment by oysteinkrog** [comment]
Hi,

I don't see why not, however I am not working actively on this project, which means that if you want it you might have to do it yourself:)
If you want to make changes and have them included, please create a pull request (from a fork) and I will take a look.

**Comment by shawnburge** [comment]
I thought about that, and it kinda scares me :P, but I'll give it a try.

Thanks!
Shawn
