### ISSUE TITLE
Cannot get SQL for: Subtract

### ISSUE THREAD

**Issue by ASheikhi82** [oysteinkrog/SQLite.Net-PCL#110]
Hi,

I'm using SQLite For Windows Phone 8.1 V3.8.7.4. When I try to select some records from the database, I get the following exception:

Cannot get SQL for: Subtract

What should I do?

**Comment by oysteinkrog** [comment]
Provide more information:)

**Comment by Shiney** [comment]
I think the issue is that the TableQuery code does not translate the "-" operator in a lambda expression to the equivalent SQL.

**Comment by oysteinkrog** [comment]
I am closing this, please reopen if the merged fix in #164 does not actually work.
