### ISSUE TITLE
Question: How to customize the connection string, to include custom PRAGMA settings?

### ISSUE THREAD

**Issue by markgibaud** [oysteinkrog/SQLite.Net-PCL#111]
I want to use the following connection string, how would I do this using SQLite-Net-PCL?

```var connectionString = string.Format("{0}; New=true; Version=3;PRAGMA locking_mode=EXCLUSIVE; PRAGMA journal_mode=WAL; PRAGMA cache_size=20000; PRAGMA page_size=32768; PRAGMA synchronous=off;",dbFilePath);```

**Comment by oysteinkrog** [comment]
Hi Mark,

I saw your tweet (prompted me to finally finally log in and clean up my hacked twitter account, so thanks).
I think you could do that by making a class that inherits from SQLiteConnectionString and sets a custom value to the ConnectionString property, or really just pass that string as the filepath parameter in SQliteConnectionString.
In the current code the filepath is passed directly to the sqlite Open function.

**Comment by markgibaud** [comment]
Thanks for the reply! I thought your twitter account looked a bit weird ;-)

From what I can see in the source, that parameter ends up going into this method in ```SQLiteApiIOS```

```public Result Open(byte[] filename, out IDbHandle db, int flags, IntPtr zvfs)
        {
            IntPtr dbPtr;
            Result r = SQLiteApiIOSInternal.sqlite3_open_v2(filename, out dbPtr, flags, zvfs);
            db = new DbHandle(dbPtr);
            return r;
        }```

But from the documentation here: https://www.sqlite.org/c3ref/open.html
It seems like there is no mention of pragmas.

Am I missing something?

I've also tried to set the pragmas manually, like this:


```var pragmas = new List<string>()
            {
                "PRAGMA journal_mode = WAL;",
                "PRAGMA locking_mode=EXCLUSIVE;",
                "PRAGMA cache_size=20000;",
                "PRAGMA page_size=32768;",
                "PRAGMA synchronous=off;"
            };

            foreach (var pragma in pragmas)
            {
                var result = await ExecuteScalarAsync<string>(pragma);
            }```

But when I read them back, they haven't changed from the defaults :-(

**Comment by markgibaud** [comment]
Ah ok - those pragmas only affect a single connection, and because I was passing in a "new SqlConnectionAsyncWithLock()" to the Func parameter, the pragmas were reset because lower down, GetConnection() was newing one up every time.

It is OK then to use the SAME connection object (so that the pragmas actually have an affect) even from multiple threads?

**Comment by oysteinkrog** [comment]
I don't think a connection is thread safe but I'm not 100% sure (you would have to ask the original authors).
Can't you just run the pragmas for each new connection?

**Comment by markgibaud** [comment]
That's possible in theory, but it seems expensive to execute several "ExecuteScalar" s on every new connection.

In the end, I've re-used the same connection across the session (and set the pragmas) and this seems to be working well, no BUSY's or LOCKED's.

Thanks!

**Comment by oysteinkrog** [comment]
Ok, good to hear you got things working:)

**Comment by molinch** [comment]
If you use the same SqlConnectionAsyncWithLock I don't think that WAL will have any effect.
This class ensures there is exactly one call at a time, so no benefits from WAL.
