### ISSUE TITLE
Failed to resolve "System.Void SQLite.Net.SQLiteConnection"

### ISSUE THREAD

**Issue by pocheshire** [oysteinkrog/SQLite.Net-PCL#113]
Issue description:
https://forums.xamarin.com/discussion/31197/mtouchtask-error-mt2002-failed-to-resolve-system-void-sqlite-net-sqliteconnection?

Are you sure you was updated dll in nuget package?

"...reference from SQLite.Net **Version=2.4.1.0**..."

**Comment by karimjouini** [comment]
Same issue here :(

**Comment by oysteinkrog** [comment]
Hi guys, I am currently traveling and do not have time/access to look at this, but I will be home in a few days and will look into it then.

**Comment by pocheshire** [comment]
Issue was solved when I compiled dll from source code

**Comment by karimjouini** [comment]
Thanks oysteinkrog, looking forward! This is blocking :(

Thanks again for your support!

**Comment by oysteinkrog** [comment]
Please check if latest nugets fix this.

**Comment by karimjouini** [comment]
now I am unable to install package on PCL :(

Could not install package 'SQLite.Net-PCL 2.5.1'. You are trying to install this package into a project that 
targets 'portable-net45+sl50+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by karimjouini** [comment]
I think this is due to UnifiedAPI support :( can you please add it?

Thanks a ton man!

**Comment by aspnetde** [comment]
Same here. Unified iOS project, too.

**Comment by alinaKava** [comment]
Same problem. Could not install package.

**Comment by oysteinkrog** [comment]
Unfortunately I no longer have access to a Xamarin license for Android/iOS, which means I can't debug this myself.
I've requested an open-source license from Xamarin, but until then I can't do much, sorry.

**Comment by pooran** [comment]
I too faced similar issues.. I hope @oysteinkrog gets his license and fixes the main build.
For now, I was able to add the nuget by selecting 'Ignore dependencies'

![sqlite](https://cloud.githubusercontent.com/assets/116028/6863718/259e1176-d47c-11e4-8a35-83cd89b31af5.png)

**Comment by oysteinkrog** [comment]
Xamarin has given me licenses now:)
Please try the prerelease of version 3.0.

**Comment by pooran** [comment]
thanks @oysteinkrog I will try it now.

**Comment by oysteinkrog** [comment]
The 3.0 prerelease was pushed out a while ago, I read in the xamarin forums post that you had issues with that version due to the resharper attributes?

**Comment by mrward** [comment]
@oysteinkrog - It looks like SQLite.Net.dll still has the attributes from the JetBrains.Annotations.PCL assembly. The [SQLite.Net project file](https://github.com/oysteinkrog/SQLite.Net-PCL/blob/6e92d1a7f951b28c6e11b42c0c05adb5d1445f2a/src/SQLite.Net/SQLite.Net.csproj#L54) is defining the JETBRAINS_ANNOTATION compiler constant which looks like it preserves the JetBrains attributes in the compiled assembly. If that is removed presumably that will fix the problem.

**Comment by pooran** [comment]
@oysteinkrog Issue still exists.. here is what I did.. 
* Created a new Xamarin Forms project, did update-package so that I am on latest Xamarin.Forms version.
* Added latest SQLite 3.0.0 beta package to all projects.

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'JetBrains.Annotations.PCL328, Version=8.0.5.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'JetBrains.Annotations.PCL328.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	SQLite3Test.Droid		

Refer https://github.com/pooran/SQLiteTest

**Comment by benschi11** [comment]
I have the same problem with my Windows 8.1 App today with version 3.0.0, 3.0.1. Cannot install 3.0.2 because it cannot resolve the dependencies.

**Comment by oysteinkrog** [comment]
@benschi11 If you had problems installing the 3.0.2-beta async nuget that was a separate problem not related to this one.

**Comment by anaximander23** [comment]
> It seems this issue only affects MonoAndroid.

Unfortunately, that doesn't seem to be the case. I'm developing a Xamarin.Forms app for iOS only. The project contains two PCLs and the iOS project, and I'm also seeing the `JetBrains.Annotations.PCL328` error when using the v3.0.3-beta NuGet package.

**Comment by benschi11** [comment]
@oysteinkrog I know that the installproblem is a different issue. But what I wanna to say is that in my Windows 8.1 app I get the JetBrains.Annotations.PCL328 as well and I tested it with the versions 3.0.0 and 3.0.1. Version 2.5.1 works fine for me.

**Comment by oysteinkrog** [comment]
Hmm ok, that sucks:/
I've made the JetBrains.Annotations nuget a dependency for all platforms now, it should fix all the problems, but I am sad that I had to resort to this to provide annotations.
I know that this solution is not the best, but I can not find any other practical solution for providing annotations. Creating xml annotations manually is just too much work.
If anyone knows a better way to do all this _please_ let me know!

**Comment by oysteinkrog** [comment]
Ok, I am closing this as I think the current prerelase nuget works, please let me know if that is not the case.

**Comment by Waaheeda** [comment]
Still facing this issue

/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void SQLite.SQLiteConnection::.ctor(System.String,SQLite.SQLiteOpenFlags,System.Boolean,System.Object)', referenced from the method 'System.Collections.ObjectModel.ObservableCollection`1<System.Object> DMI.Xip.PlatformModule.Dal.Services.LookupService::GetLookupData(System.String,System.String)' in 'SQLite-net, Version=1.5.231.0, Culture=neutral, PublicKeyToken=null'. (MT2101)
