### ISSUE TITLE
Problem converting DateTime after converting from MvvmCross SQLite Plugin

### ISSUE THREAD

**Issue by erviem99** [oysteinkrog/SQLite.Net-PCL#119]
Hello!

I just finished migrating from MvvmCross SQLite Community Plugin to SQLite.Net-PCL and now I have a problem where DateTime fields cannot be read (on iOS - haven't tried om Android).

If I create an empty database with SQLite.Net-PCL there are no problems, so I guess there must be some kind of DateTime configuration that I'm missing?

Regards
Erik

**Comment by erviem99** [comment]
I think I found out what is going on as per this thread:

https://github.com/MvvmCross/MvvmCross/issues/213

My guess is that my DateTime's are stored at strings and SQLite.Net-PCL uses ticks.

**Comment by oysteinkrog** [comment]
I think there is a constructor option for that (using ticks or string).

**Comment by ilber** [comment]
The big problem here is the migration from the previous version of the app to the new one. The old one uses Ticks and reading a value from the DB returns the UTC date time.
If I set the property user strings now, the old values will crash the app.
Anyone has an Idea why the Ticks of the datetime are not converted correctly to the stored datetime?

**Comment by hemantksh** [comment]
The **SQLiteConnection** constructor takes a parameter **storeDateTimeAsTicks** which defaults to true. You can pass that as false if you want it to use a DateTime type instead of bigint.
