### ISSUE TITLE
How do queries on sqlite_master?

### ISSUE THREAD

**Issue by 3green** [oysteinkrog/SQLite.Net-PCL#129]
Hi what is the best way to do queries on SQLite_master? I have tried the Query<T>(...) but cant seem to get it to recognise SQLite_master as a table. 
Many thanks

**Comment by oysteinkrog** [comment]
Hi, I'm sorry but I don't know.
Perhaps someone else does?

**Comment by Shiney** [comment]
You can use 
        [Table("sqlite_master")]
        public class SqliteSchemaObject
        {
            public string type { get; set; }
            public string name { get; set; }
            public string tbl_name { get; set; }
            public int rootpage { get; set; }
            public string sql { get; set; }
        }

As the class that represents the schema objects (You can use the Column attribute to have a different naming convention)

Then you can get all the objects in the database using:

db.Table<SqliteSchemaObject>()
