### ISSUE TITLE
Transaction + guid primary keys does not work under WinRT

### ISSUE THREAD

**Issue by davesmits** [oysteinkrog/SQLite.Net-PCL#138]
got a scenario where:
foreach (var evt in events)
                    table.InsertOrReplace(evt); works but 
table.InsertOrReplaceAll(events) results in a error:
sql logic error or database missing

**Comment by oysteinkrog** [comment]
Hm, could you please provide a test that reproduces this?

**Comment by davesmits** [comment]
here you are!

https://onedrive.live.com/redir?resid=D1BA3C73BE854A97!198068&authkey=!ACt9wS0v81ywCxw&ithint=file%2czip

**Comment by oysteinkrog** [comment]
Thanks,

The difference between InsertOrReplace and InstertOrReplaceAll is that the latter wraps the statements in a transaction.
I can reproduce it in your test project, but not when using the win32 platform.
By switching from guid primary keys to int (autoincrement) it works...

**Comment by oysteinkrog** [comment]
Trace output with values:

Executing: create table if not exists "DataObject"(
"Id" varchar(36) primary key not null ,
"Text" varchar )
Executing Query: pragma table_info("DataObject")
Executing: savepoint S22338D0
Executing: insert OR REPLACE into "DataObject"("Id","Text") values (?,?), Values: 7f1d89d6-8fb1-480c-a9ff-4797418b3457 1
Executing: insert OR REPLACE into "DataObject"("Id","Text") values (?,?), Values: 11022ead-036a-4b3e-b842-10d792282725 2

I'm not really sure SQLite.Net does anything wrong here?
One thing I am not sure about is the way we store guids, they are stored as strings right now, but it looks like it is also possible to use blobs.
Adding ";BinaryGUID=False" to the connection string made no difference.

**Comment by davesmits** [comment]
i think this one is very related to it: https://github.com/oysteinkrog/SQLite.Net-PCL/issues/75

**Comment by oysteinkrog** [comment]
The merge of #157 may help with this, please test prerelease version (3.0.2).

**Comment by igrali** [comment]
@oysteinkrog I have a similar problem with WP8, but not with Generic platform. Similar as it fails during insert/replace, even though no guids are involved.

I have tried with the 3.0.2 version and no luck - the same thing happens again. Any new ideas what could be wrong? Thanks!

**Comment by oysteinkrog** [comment]
Hmm, well the WP8 platform does not set the temp directory.
If you could test/verify if that fixes it we can add it there too.
As you can see the code is currently commented out:
https://github.com/oysteinkrog/SQLite.Net-PCL/blob/master/src/SQLite.Net.Platform.WindowsPhone8/SQLitePlatformWP8.cs
Can you test if setting the directory fixes your issue?
You should be able to test by just doing the same/similar as the WinRT platform:
https://github.com/oysteinkrog/SQLite.Net-PCL/blob/master/src/SQLite.Net.Platform.WinRT/SQLiteApiWinRT.cs#L14

**Comment by igrali** [comment]
Trying! Thanks for your quick response.

**Comment by igrali** [comment]
That won't work unfortunately, no TemporaryFolder on Windows Phone 8. So it must be something else causing it.

That's probably the same issue that @eugenioestrada was having https://github.com/oysteinkrog/SQLite.Net-PCL/issues/114 but there's no solution mentioned there.

**Comment by davesmits** [comment]
I think something is wrong with the nugget package: 
Could not load file or assembly 'JetBrains.Annotations.PCL328, Version=8.0.5.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' or one of its dependencies. The system cannot find the file specified.

**Comment by igrali** [comment]
I found this StackOverflow question:

http://stackoverflow.com/questions/20474253/sqlite-3-8-2-exception-on-update-statement

I's pretty old, but the suggestion there actually helped in my case - I downloaded the old VSIX just for Windows Phone 8 and it's not crashing anymore. Very strange, but I hope this helps others too!
