### ISSUE TITLE
SQLite Consistent Naming

### ISSUE THREAD

**Issue by prasannavl** [oysteinkrog/SQLite.Net-PCL#143]
Hi, 

This is a very trivial one. But I was wondering, if along with the new v3 branch, a renaming of all the types with the prefix "SQLite" or "SQLLite", to "Sqlite", conforming to Microsoft's abbreviation convention, would be considered. Should just be a simple refactor, and would make the code look a lot more consistent when used in combinations with other projects conforming to the standard.

Just a thought :)

**Comment by oysteinkrog** [comment]
Hehe, well I think naming is important, and I'm not sure the current naming is "correct", _but_ I really don't think it's worth it to change it now.
