### ISSUE TITLE
.NET 4 support

### ISSUE THREAD

**Issue by Shiney** [oysteinkrog/SQLite.Net-PCL#146]
The library currently targets .net45. Is there any reason why it shouldn't support .net 4, other than the fact it currently uses reflection APIs that are not in .net 4?

I am happy to make the changes to make this work if you think it is a good idea.

**Comment by oysteinkrog** [comment]
Hmm, well yes I did do that on purpose.
I am reluctant to add back .net4 support as I fear it would complicate both the codebase and the build system, for relatively little gain.
What would your strategy for implementing it be?

**Comment by Shiney** [comment]
Switch the profile to include .net 4 and replace the calls to .net4.5
reflection APIs with ones compatible with .net 4. I wouldn't be suggesting
anything like conditional compilation as it isn't necessary.

**Comment by oysteinkrog** [comment]
Ah I see,
That would change it from Profile259 to Profile328.
The async project would still be .net 4.5 then?

**Comment by Shiney** [comment]
I'm not sure. I think since async/await isn't actually used in the async
project that won't be necessary as you can still use async/await if you are
calling a .NET4.0 library from .NET4.5, but if that were a problem then
your suggestion would be the solution.

**Comment by oysteinkrog** [comment]
#149
