### ISSUE TITLE
Inserting data with PrimaryKey: InsertOrReplaceAllAsync() fails, while ExecuteAsync() succeeds

### ISSUE THREAD

**Issue by Aurora12** [oysteinkrog/SQLite.Net-PCL#148]
I'm building a universal store project for Windows 8.1 and Windows Phone 8.1.

* SQLite for Windows Runtime (Windows 8.1) v. 3.8.8.3
* SQLite.Net.Async PCL  v. 2.5.1
* SQLite.Net PCL - WinRT Platform v. 2.5.1

Here's some test code stripped of everything irrelevant.

```
[Table("Users")]
public class DBUser : ITable
{
	[PrimaryKey]
	public long Id { get; set; }
}
```

```
Connection = new SQLiteConnectionWithLock(
  new SQLitePlatformWinRT(),
  new SQLiteConnectionString(
	Path.Combine(ApplicationData.Current.LocalFolder.Path, "users1.db"),
	true
  )
);
Database = new SQLiteAsyncConnection(() => Connection);
await Database.DropTableAsync<DBUser>();
await Database.CreateTableAsync<DBUser>();

// Fails with "SQL logic error or missing database"
/*
int result = await Database.InsertOrReplaceAllAsync(new List<DBUser>(){
  new DBUser(){ Id=123123123L },
  new DBUser(){ Id=456456456L }
});
*/

// Succeeds
int result = await Database.ExecuteAsync("INSERT OR REPLACE INTO Users(Id) VALUES(123123123),(456456456)");

List<DBUser> list = await Database.Table<DBUser>().ToListAsync();
Debug.WriteLine(list.Count);
Debug.WriteLine(list[0].Id);
Debug.WriteLine(list[1].Id);
```

Comment `[PrimaryKey]` attribute in DBUser and both inserts work just fine.
Am I doing something wrong?

**Comment by StefanFabian** [comment]
If you don't need it, I'd strongly recommend you don't use the async version.
It seems to be a little buggy.
If I recall correctly I had the same issue and it was resolved when I iterated the list myself and called InsertOrReplaceAsync(...) on each one.
But it might also have something to do with you using long as PrimaryKey.
There were some issues regarding longs as primary keys.

**Comment by Aurora12** [comment]
@StefanFabian Hmm. `int` primary key *works fine*, while `long` or `string` doesn't. I'll try to use synchronous version, thanks for the hint. I can wrap sqlite operations in tasks anyway.

**Comment by Aurora12** [comment]
@StefanFabian I removed async library from my project, but the problem persists. :(

**Comment by StefanFabian** [comment]
Take a look at this: https://github.com/oysteinkrog/SQLite.Net-PCL/issues/144
and this https://github.com/praeclarum/sqlite-net/commit/eea78a75b820c12d9a1b5b306a4ff32458dd2098

is there a reason why it needs to be long?
can't you use an int?

**Comment by Aurora12** [comment]
Unfortunately, I do need a long. These are entities I get from server side. And since I build a mobile app, it has to cache data locally so as to allow viewing stuff in offline mode. I need ids just as server outputs them.

**Comment by oysteinkrog** [comment]
In the 3.0 prerelease nuget that is out now, the int64-as-integer fix is included.
If possible please test that version (just select prerelease in the nuget explorer and it should show up).

**Comment by oysteinkrog** [comment]
The merge of #157 may also help with this, please test prerelease version (3.0.2).

**Comment by Aurora12** [comment]
Will try this today on both desktop and mobile, thanks a lot!

**Comment by Aurora12** [comment]
Works fine btw, thanks (sorry for not updating you before)!
