### ISSUE TITLE
No foreing keys support?

### ISSUE THREAD

**Issue by MihaMarkic** [oysteinkrog/SQLite.Net-PCL#165]
Hi guys,

Is there a foreign key support currently? It doesn't look so.

**Comment by igrali** [comment]
No, not in this library.

There's the SQLite-Net Extensions library that can be used with this one to have FK support. https://bitbucket.org/twincoders/sqlite-net-extensions

**Comment by MihaMarkic** [comment]
Ah, ok. It'd be nice, though, to have an attribute that would enforce FK. Perhaps I'll add it, would it make sense?

**Comment by Mutantpenguin** [comment]
The SQLite-Net Extensions library does exactly that!
