### ISSUE TITLE
UInt64 (ulong) as a field type is not supported

### ISSUE THREAD

**Issue by belyansky** [oysteinkrog/SQLite.Net-PCL#175]
```C#
[Table("Items")]
public class Item
{
    [PrimaryKey]
    [AutoIncrement]
    public int Id { get; set; }

    public ulong Foo { get; set; }
}
```

System throws an exception when trying to create a table with the definition from above:
```
System.NotSupportedException: Don't know about System.UInt64
```
With types such as long, uint, ushort etc. all works fine.

**Comment by oysteinkrog** [comment]
Afaik sqlite does not support unsigned 64-bit integer, only signed.
http://www.sqlite.org/datatype3.html#storageclasses
http://stackoverflow.com/questions/15201776/retrieving-ulong-from-sqlite-relsults-in-notsupportedexception

**Comment by sharpwood** [comment]
Can we solve this problem through custom function ?
