### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by FunThom** [oysteinkrog/SQLite.Net-PCL#183]
Hi,

is .net40 still supported in the current version 3.0.5?
Nuget currently fails in my .net40 PCL. I got the same error for every version after 2.3.0.

Error: Could not install package 'SQLite.Net-PCL 3.0.5'. You are trying to install this package into a project that targets 'portable-win+net40+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by oysteinkrog** [comment]
Hi FunThom, .net 4.0 is no longer supported in the nuget.
If you really need .net 4.0 support I recommend you just fork and build yourself:)

**Comment by FunThom** [comment]
Hi oysteinkrog,
thanks for the answer. I'll try that. :)

**Comment by Giorgi** [comment]
You can use 3.0.5 version of the package:

> Install-Package SQLite.Net-PCL -Version 3.0.5
