### ISSUE TITLE
[Windows Phone 8]Unable to connect to db in ApplicationData.Current.LocalFolder

### ISSUE THREAD

**Issue by CartBlanche** [oysteinkrog/SQLite.Net-PCL#190]
I think I'm doing the right thing within this gist to check if my db exists on WP8.x, copy from resource to isolated storage, then establish a connection to it...
https://gist.github.com/CartBlanche/ea7f01d30b3f564e5e87

But the connection *always* fails with a  "FileNotFound" exception on Windows Phone, even though the file exists (when re-running it doesn't try to copy the DB again). I'm using an 8.1 Emulator if that makes any difference.

Similar connection code for iOS and Android works flawlessly, so thanks team for that!!

@ncipollina @micahl @vladstoick  any suggestions? Have I missed something obvious? 
Apologies if this is a newbie question, but my first WP app and Google hasn't enlightened me.

Thanks,

Dominique.

**Comment by igrali** [comment]
Instead of 

    iso.CreateFile (filename)

have you tried doing

    iso.CreateFile (fullPath)

where fullPath is essentially this:

    string fullPath = Path.Combine (ApplicationData.Current.LocalFolder.Path, sqliteFilename);

**Comment by CartBlanche** [comment]
@igrali Yes I did that originally, by accident. That didn't work as ApplicationData.Current.LocalFolder.Path returns a C:\\AppData\Users\........ location, which it then tries to create from the isolated storage location and throws an invalid storage error.

**Comment by ncipollina** [comment]
@CartBlanche, is the issue that it can't find your database file, or that it can't find the Sqlite extension.  My guess is that it is perhaps the latter.  Right-click on your References and go under Extensions and make sure you have included a reference to Sqlite.

**Comment by CartBlanche** [comment]
@ncipollina I had totally overlooked that Sqlite reference step. :( Now it works as advertised. Thanks again and keep up the awesome work!!! I'll close this issue.
