### ISSUE TITLE
Windows 10 UAP - PrimaryKey is not valid...

### ISSUE THREAD

**Issue by Sun3** [oysteinkrog/SQLite.Net-PCL#200]
When I am trying to create the Table Class I receive below error on the ``` [PrimaryKey, AutoIncrement]
 ```  The same error if I add the ``` [Indexed]  ```

This is creating a Windows 10 Universal App.
```
public class Stock
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }
    [MaxLength(8)]
    public string Symbol { get; set; }
}
```

Error:
Error	CS0592	Attribute 'PrimaryKey' is not valid on this declaration type. It is only valid on 'property, indexer' declarations.

Any thoughts?
Thanks

**Comment by Sun3** [comment]
This can be closed. It's all working now. I placed my code below just in case it might help someone else.

```
        //[PrimaryKey, Unique] // Here it was failing
        private string id_category;
        [PrimaryKey, Unique] // Here it works great
        public string Id_Category
        {
            get { return id_category; }
            set
            {
                if (value != id_category)
                {
                    id_category = value;
                    OnPropertyChanged("Id_Category");
                }
            }
        }
```

**Comment by oysteinkrog** [comment]
Thanks for updating:)
