### ISSUE TITLE
DateTime Storage, why Ticks?

### ISSUE THREAD

**Issue by Schlumpf9** [oysteinkrog/SQLite.Net-PCL#203]
I saw that DateTime is stored as bigint in SQLite. Why it isn't stored in Datetime Format 2012-08-28 08:35:33 or as Unix Timestamp?

When I use DateTime.Now in C# I have this number stored: 635742203345490322. How can I work with that number in a SQLite Select?!
SELECT strftime("%d.%m.%Y",635742203345490322); results in 06.10.-471 ...

I googled and found this:
SELECT strftime('%Y-%m-%d %H:%M:%S', 635742203345490322 / 10000000 - 62135596800, 'unixepoch','localtime')
which returns 2015-08-03 19:38:54 as it should. But this solution is in my eyes shit... Any other solutions? Would be great if a timestamp or something can be stored...

Greets

**Comment by oysteinkrog** [comment]
Hum well I understand what you are saying, this is simply how the library was written originally.
If you want to change it you can:)

**Comment by hemantksh** [comment]
Hello @Schlumpf9,
I came across the same issue. Here's an option:
The **SQLiteConnection** constructor takes a parameter **storeDateTimeAsTicks** which defaults to true. You can pass that as false if you want it to use a DateTime type instead of bigint.

**Comment by torrobinson** [comment]
Thanks @hemantksh! I was having the weirdest issues saving and loading dates consistently using the built-in `DateTime` format. Then I inspect our Db on the iPhone to see that it's storing dates as ticks for some unknown reason. 

Turning this off solved all my problems!
