### ISSUE TITLE
Windows10, VisualStudio2015, System.NotSupportedException

### ISSUE THREAD

**Issue by StyrianOak** [oysteinkrog/SQLite.Net-PCL#206]
After moving to Windows10 I get the error "System.NotSupportedException" in SQLite.Net.dll, additional info is "Cannot compile: Parameter".
The statement when I get the error is 
(From s In MyDb.Table(Of Song)()
              Where (s.GetArtist = ArtistName)).OrderBy(Function(x) x.Songname)

Think it has to do mainly with Win10, not VS2015 ?
Maybe there's any help ?

Thx in advance !

**Comment by StyrianOak** [comment]
It's working again with the new version 3.1. thank you !

**Comment by oysteinkrog** [comment]
Strange, but good :)
