### ISSUE TITLE
Move the core SQLite.Net.dll into a new NuGet

### ISSUE THREAD

**Issue by mattleibow** [oysteinkrog/SQLite.Net-PCL#207]
As mentioned in issue #201, the platform specific assemblies are moved into the main assembly.
Unfortunately, this causes problems when creating a new platform implementation, such as when trying to create an implementation for an encrypted database.

What about having 3 NuGets? 

  1. SQLite.Net.Core 
     - SQLite.Net.dll
  2. SQLite.Net.Async -> SQLite.Net
     - SQLite.Net.Async.dll
  3. SQLite.Net -> SQLite.Net
     - SQLite.Net.Platform.*.dll

Then, when I need to create my own platform implementation, I can just depend on SQLite.Net?

If this seems good, I'll create a PR.

**Comment by oysteinkrog** [comment]
This was my original design, but it seems like very few people actually need this.
I am a bit reluctant to messing with the nuget structure again, it was annoying enough for everyone the last time I think.

**Comment by mattleibow** [comment]
I am needing this for work with SQLCipher. They have their own platform and are having to introduce complexities due to the NuGet including a platform. My change should not affect the current users, and all updates should not be noticeable.
Maybe the community can vote on this and see what happens?

**Comment by oysteinkrog** [comment]
Hmm, it is a good point that this change would be automatically handled by nuget.

**Comment by mattleibow** [comment]
We just need to let the community know that they need to depend on SQLite.Net.Core if they want to be compatible with other platforms, such as SQLCipher.

**Comment by developernotes** [comment]
Hello @oysteinkrog 

This is great news, any chance on a new nuget release?  This will allow us to add a dependency on the new SQLite.Net.Core package.

**Comment by mattleibow** [comment]
Hi @oysteinkrog,
Not to be a nuisance, but is there any vague timeline for a release?
Even a pre-release version will do. We just want to try out some things with the split packages.

**Comment by oysteinkrog** [comment]
Hi guys, sorry about the lack of reply :/
I'll try to get a new release out this weekend, but keep in mind that it's easy to create your own packages or even just use the source directly.

**Comment by developernotes** [comment]
Hi @oysteinkrog 

Thanks, that would be awesome!  We actually need to reference the updated nuget package, we look forward to a new release.  Thanks again!

**Comment by developernotes** [comment]
Hi @oysteinkrog 

I just wanted to touch base with you to see if you would be able to release a new build of SQLite.Net-PCL?  Thanks!

**Comment by sjlombardo** [comment]
Hi @oysteinkrog I was wondering if you might have a quick update on the schedule for the next planned release? We've done a lot of testing with our own builds, but would love to provide the ability for users to use an official NuGet release.

My colleague @developernotes also mentioned this in #211 last week, but the SQLCipher team from Zetetic would be happy to help maintain the SQLite.Net-PCL project, in any capacity you'd like, if you are busy and it would help reduce your workload.

**Comment by oysteinkrog** [comment]
@sjlombardo: Thank you for the offer, I've decided I will try to spend a bit more time on the project, in order to maintain it properly.

**Comment by developernotes** [comment]
@oysteinkrog thanks!
