### ISSUE TITLE
Once again DateTime with SQLite, but a new one

### ISSUE THREAD

**Issue by Schwenkner** [oysteinkrog/SQLite.Net-PCL#226]
I've read a lot about problems with DateTime fields in SQLite. But what I considered is not discussed yet.

I have a database with a table containing a DateTime field. I created and inserted data using InsertAsync. Since I want to use relations bewtween other tables, I Use also the extensions. When I read all record using an AsyncConnection, the DateTime fields are filled properly. Unfortunately the async extensions don't support GroupBy. So I decided to implement in parallel also sync Connection which supporty GroupBy. Now, when I read the data uing syncConnection.Table<MyTable>(), the datetime fields have always the value 01.01.0001 Reading the data with an asyncConnection, the datetime fields are correct.

I have also tried to initialliy create and fill the database with sync methods, but the same behaviour. Reading with sync methods doesn't fill datetime fields correct, but the async methods do.

Now, since I knew the async methods are only wrapper methods to the sync ones, I do not understand why this happens.

**Comment by oysteinkrog** [comment]
Could you try to create a test that reproduces this issue?

**Comment by Schwenkner** [comment]
I've dived a bit more into my problem. And it seems, the fault was on my side.

Before first access I created the database and filled it with test data. UWP only supports async access to the file with the test data. And it seemed that database was not ready with filling in the test data while I'm already trying to read them.

With properly waiting until initialization is done, it seems to work.

**Comment by oysteinkrog** [comment]
Ok, thanks for updating :)
