### ISSUE TITLE
Adding interfaces

### ISSUE THREAD

**Issue by aloisdeniel** [oysteinkrog/SQLite.Net-PCL#227]
For mocking purpose it could be great to have interfaces on top of SQLiteConnection class.

**Comment by oysteinkrog** [comment]
I agree :)

**Comment by seanfisher** [comment]
I extracted an interface for SQLiteAsyncConnection [in this gist](https://gist.github.com/seanfisher/cb51e149575da077103700a088e9394e), if that helps.
