### ISSUE TITLE
 database is locked

### ISSUE THREAD

**Issue by gregduffield** [oysteinkrog/SQLite.Net-PCL#231]
I am using this for an Android (Xamarin MVVMCross) solution and we are getting a lot of database locked errors however the platform api has been configured for serialised access as per below

    var platform = new SQLite.Net.Platform.Generic.SQLitePlatformGeneric();
    var g = new SQLite.Net.Platform.Generic.SQLiteApiGeneric();
    g.Config(SQLite.Net.Interop.ConfigOption.Serialized);
    var _conn = new SQLiteConnection(platform, _path);

Any suggestions?

Thanks

Greg

**Comment by oysteinkrog** [comment]
Sorry no, I suspect this is a sqlite issue, not a problem with SQLite.Net.

**Comment by Jerome2606** [comment]
Hello @gregduffield ,

I have the same issue actually, Can you point me to what you are using now to fix this problem ?

Thanks
