### ISSUE TITLE
Can't be added to PCL in VS2015

### ISSUE THREAD

**Issue by haseebahmed7** [oysteinkrog/SQLite.Net-PCL#232]
I just created a simple PCL in VS2015 which targets the following platforms:
* .NET 4.5
* Silverlight 5
* Android
* iOS
* iOS (Classic)

Now when I try to add this via NuGet, I get the following error:
> Could not install package 'SQLite.Net-PCL 3.0.5'. You are trying to install this package into a project, that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any, assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by oysteinkrog** [comment]
I don't think Silverlight 5 is supported any more.

**Comment by haseebahmed7** [comment]
@oysteinkrog why is that? It turns out that Silverlight 5 is automatically added into any PCL that you create using VS2015.

**Comment by oysteinkrog** [comment]
This is the PCL setup for the core project:
http://imgur.com/vqqhO5u

**Comment by haseebahmed7** [comment]
I guess the reason it was adding Silverlight 5 is because I wasn't selecting any of the Windows platforms. Selecting it the way it is described in the image above solved the issue.
Thanks!
