### ISSUE TITLE
incorporating changes from praeclarum

### ISSUE THREAD

**Issue by tofutim** [oysteinkrog/SQLite.Net-PCL#238]
Hi, just curious if you ever pulled in changes from praeclarum, is that needed or helpful?

**Comment by oysteinkrog** [comment]
Yes, I have pulled in a lot of the changes that were added since I forked, though I know there are a few that are missing (e.g. db events).

**Comment by tofutim** [comment]
A thought, if the location of the two .cs files are the same, it might be easier to compare between branches.

**Comment by tofutim** [comment]
I suppose it is quite different now though.

**Comment by tofutim** [comment]
I've been comparing the code and commits, and indeed, looks like you have pulled in most of the changes.

**Comment by oysteinkrog** [comment]
Well the overall structure of the code is extremely different (split into multiple files and lots of other changes), but I have tried to cherry-pick and port most stuff.
