### ISSUE TITLE
PCLStorage

### ISSUE THREAD

**Issue by tofutim** [oysteinkrog/SQLite.Net-PCL#239]
VS2015, after restoring packages, I still find that PCLStorage is not picking up, are you using something other than nuget to get this? Should I update the nuget?

**Comment by tofutim** [comment]
I think some how the Path hint was not working for me, I uninstalled and re-installed.

**Comment by tofutim** [comment]
Here's how it looks different after i make that change:

index 77ebaf8..36801d9 100644
--- a/tests/SQLite.Net.Tests.Generic/SQLite.Net.Tests.Generic.csproj
+++ b/tests/SQLite.Net.Tests.Generic/SQLite.Net.Tests.Generic.csproj
@@ -46,12 +46,12 @@
       <HintPath>..\..\packages\NUnit.2.6.4\lib\nunit.framework.dll</HintPath>
       <Private>True</Private>
     </Reference>
-    <Reference Include="PCLStorage">
-      <HintPath>C:\WORK\REPOS\SQLite.Net PCL\packages\PCLStorage.1.0.2\lib\net45\PCLStorage.dll</HintPath>
+    <Reference Include="PCLStorage, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64, processorArchitecture=MSIL">
+      <HintPath>..\..\packages\PCLStorage.1.0.2\lib\net45\PCLStorage.dll</HintPath>
       <Private>True</Private>
     </Reference>
-    <Reference Include="PCLStorage.Abstractions">
-      <HintPath>C:\WORK\REPOS\SQLite.Net PCL\packages\PCLStorage.1.0.2\lib\net45\PCLStorage.Abstractions.dll</HintPath>
+    <Reference Include="PCLStorage.Abstractions, Version=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64, processorArchitecture=MSIL">
+      <HintPath>..\..\packages\PCLStorage.1.0.2\lib\net45\PCLStorage.Abstractions.dll</HintPath>
       <Private>True</Private>
     </Reference>
     <Reference Include="System" />

**Comment by oysteinkrog** [comment]
Merged your fixes for this, thanks :)
