### ISSUE TITLE
appveyor.yml file is case-sensitive

### ISSUE THREAD

**Issue by tofutim** [oysteinkrog/SQLite.Net-PCL#242]
Apparently it has to be all lower case - but of course on Windows and git there is madness, so I renamed it _appveyor.yml from Appveyor.yml and then renamed it to appveyor.yml. Now it looks like it can find the solution and a new error appears

Error parsing the nested project section in solution file. A project with the GUID "{38AF8105-65B6-4A14-A258-1137D9E40EF1}" is listed as being nested under project "{59584026-7610-4CD5-A74E-D2B0A2E1CE87}", but does not exist in the solution.

**Comment by tofutim** [comment]
Probably this is a vestige from the larger solution. Looks like there are 3 nested projects under Platforms, and 38AF8105 is no longer there. BTW, 38AF8105 is also referenced but missing from SQLite.Net.sln. Maybe an old something...

**Comment by oysteinkrog** [comment]
Merged/included your fixes for this, thanks :)
