### ISSUE TITLE
CallsOnUnsupportedTypes failing

### ISSUE THREAD

**Issue by tofutim** [oysteinkrog/SQLite.Net-PCL#243]
Should this test be passing? It fails at Assert.That(types, Has.Member(typeof (DateTimeOffset))); but it seems that no types are ever added by the Serializer.

**Comment by tofutim** [comment]
https://github.com/oysteinkrog/SQLite.Net-PCL/issues/196 suggest that this test can be ignored and that DateTimeOffset may already be supported. Looks like the test for Guid also fails.

**Comment by tofutim** [comment]
DateTimeOffset is defined in Orm.cs as a bigint, so it is supported.

**Comment by tofutim** [comment]
I fixed this in my PR by adding a DivideByZeroException as the not supported type. For the saving, I used Newtonsoft.Json to serialize but really it could be something else.

**Comment by oysteinkrog** [comment]
Awesome :)
