### ISSUE TITLE
3.1.1 Nuget Release Issue

### ISSUE THREAD

**Issue by developernotes** [oysteinkrog/SQLite.Net-PCL#247]
Hi @oysteinkrog 

With the latest `3.1.1` release, it appears that the SQLite.Net.dll package includes the wrong version of the file, specifically it is including the `3.1.0.0` version instead.  This may be the case for the SQLite.Net or SQLite.Net.Async packages, I have just verified against the SQLite.Net.Core package.

Executing the following:

    nuget install SQLite.Net.Core-PCL -Version 3.1.1 -OutputDirectory .

If you look at the file version of `SQLite.Net.dll` found in the `SQLite.Net.Core-PCL.3.1.1\lib\portable-win8+net45+wp8+wpa81+MonoAndroid1+MonoTouch1` directory, it displays `3.1.0.0`.

Performing an install of `3.1.0` and then comparing the SHA1 shows the files are identical:

```
C:\Users\nparker\Desktop>openssl dgst -sha1 "SQLite.Net.Core-PCL.3.1.0\lib\portable-win8+net45+wp8+wpa81+MonoAndroid1+MonoTouch1\SQLite.Net.dll"
SHA1(SQLite.Net.Core-PCL.3.1.0\lib\portable-win8+net45+wp8+wpa81+MonoAndroid1+MonoTouch1\SQLite.Net.dll)= cd1c530c2a426565b55033692974adaa95cd9f2d

C:\Users\nparker\Desktop>openssl dgst -sha1 "SQLite.Net.Core-PCL.3.1.1\lib\portable-win8+net45+wp8+wpa81+MonoAndroid1+MonoTouch1\SQLite.Net.dll"
SHA1(SQLite.Net.Core-PCL.3.1.1\lib\portable-win8+net45+wp8+wpa81+MonoAndroid1+MonoTouch1\SQLite.Net.dll)= cd1c530c2a426565b55033692974adaa95cd9f2d
```

**Comment by oysteinkrog** [comment]
This is correct, the 3.1.1 release only changed some stuff in the nuget packages, not source :)

**Comment by developernotes** [comment]
Ok, thanks @oysteinkrog!
