### ISSUE TITLE
Create database from a Windows Phone signed app fails

### ISSUE THREAD

**Issue by eugenioestrada** [oysteinkrog/SQLite.Net-PCL#25]
Hi, I've published an app as a Beta and the app cannot create the database file (in debug mode it works). It seams to be something similar to the exposed in this link: http://developer.nokia.com/community/wiki/How_to_use_SQLite_in_Windows_Phone.

I've tried to copy the database file to included it as content, but I don't find where the file is being created.

The unsigned app works correctly.

**Comment by Depechie** [comment]
Had some similar problems and documented them on my blog... Maybe the pre compiler part could be looked at for the readme too? http://depblog.weblogs.us/2015/01/06/sqlite-net-and-sqlite-net-extensions-with-universal-apps/

**Comment by oysteinkrog** [comment]
Hmm that blog posts seems to confuse the original sqlite-net project and this fork.
I created this fork for PCL support and I've ended up incorporating lots of fixes and features.
What makes everything even more confusing is that the original project also has PCL support now! :P
I've never done much WP development and I've barely event tested that code, it's primarily from contributors.
If anyone has some suggestions for improvements in the readme please send a pull request!

**Comment by reader-man** [comment]
@oysteinkrog Should we use the same tutorial:
http://code.tutsplus.com/tutorials/an-introduction-to-xamarinforms-and-sqlite--cms-23020
