### ISSUE TITLE
New NuGet Content Management System

### ISSUE THREAD

**Issue by charlesmilette** [oysteinkrog/SQLite.Net-PCL#257]
NuGet released 3.3  
[According to the changelog, it uses a new way to manage content.](http://blog.nuget.org/20151118/nuget-3.3.html)  
Trying to install the package with the latest version of NuGet will copy no files, the package needs to use the new system.  
Can this be fixed, so I can install this package and actually use it on an Universal Windows app?

**Comment by oysteinkrog** [comment]
I'm not sure I understand, the nugets for this project do not use any content files?
Perhaps you are thinking of the nuget(s) for the original project? (this project is a fork).

**Comment by charlesmilette** [comment]
Oops... Sorry for the disturbance.

**Comment by oysteinkrog** [comment]
No worries!
