### ISSUE TITLE
Unable to install SQLite.Net.Core-PCL into Xamarin PCL

### ISSUE THREAD

**Issue by engenb** [oysteinkrog/SQLite.Net-PCL#258]
My PCL project platform targets:
Xamarin.Android
Xamarin.iOS
Xamarin.iOS (Classic)
.NET Framework 4.5 (defaulted via xamarin targets)
Silverlight 5 (also defaulted via xamarin targets)

I get that the error output is telling me the supported platforms of your library and my pcl don't jive, but it's my understanding that your library supports the above platforms, so any guidance would be appreciated.  Thanks!

Package Manager Console log:
```
PM> Install-Package SQLite.Net.Core-PCL
Attempting to gather dependencies information for package 'SQLite.Net.Core-PCL.3.1.1' with respect to project 'RedArrow.Engage.Mobile.Domain', targeting '.NETPortable,Version=v4.0,Profile=Profile24'
Attempting to resolve dependencies for package 'SQLite.Net.Core-PCL.3.1.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'SQLite.Net.Core-PCL.3.1.1'
Resolved actions to install package 'SQLite.Net.Core-PCL.3.1.1'
Install failed. Rolling back...
Package 'SQLite.Net.Core-PCL.3.1.1 : ' does not exist in project 'RedArrow.Engage.Mobile.Domain'
Package 'SQLite.Net.Core-PCL.3.1.1 : ' does not exist in folder 'C:\Engage\Trunk.Delta\packages'
Install-Package : Could not install package 'SQLite.Net.Core-PCL 3.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package SQLite.Net.Core-PCL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ```

**Comment by engenb** [comment]
Figured it out - little new to PCLs.  My project must target:
.NET Framework 4.5
Windows 8
Windows Phone 8.1
Windows Phone Silverlight 8
Xamarin.Andriod
Xamarin.iOS
Xamarin.iOS (Classic)

I had thought, since my library is less restrictive from an api standpoint, that I'd be able to pull in your more restrictive (supports more platforms) project.  Looks like they need to match for build profiles for nuget to be happy.  If this is not the case, please let me know!

**Comment by oysteinkrog** [comment]
Well, the fact that you had Silverlight 5 in your targets made your library more restrictive:)
The choice to drop SL5 was not easy, but it was really holding us back.

**Comment by engenb** [comment]
maybe an odd question, but then how do I NOT target Silverlight 5?  The only target platforms I really need are .NET, Xamarin.Android, and Xamarin,iOS.  But, if I choose those 3 it auto-includes Silverlight 5.
