### ISSUE TITLE
PCL SQLite.Net.Platform

### ISSUE THREAD

**Issue by dev-nextprogress** [oysteinkrog/SQLite.Net-PCL#261]
Many thanks for the great work !
I was trying to use this in a pcl 259 profile and thought that the SQLite.Net.Platform.Generic would be the respective ISQLitePlatform implementation but from what I saw this is a .NET45 project, not PCL.
Is there a true PCL Platform interface implementation for ISQLitePlatform or am I missing something ?
Thanks much
dev

**Comment by dev-nextprogress** [comment]
I guess I should read the documentation more thoroughly. So what I understand is that there is not a PCL Platform ISQLitePlatform implementation. I know how difficult this is, so don't take this as criticism. Before I look into trying it myself, does anyone have plans to do this already ?

**Comment by oysteinkrog** [comment]
It's not possible to do that with a proper sqlite backing, as PCL does not support pinvoke.
You could use a pure C# sqlite re-implementation though.

**Comment by dev-nextprogress** [comment]
Gor it, thanks for replying swiftly
