### ISSUE TITLE
Save custom types to sqlite database

### ISSUE THREAD

**Issue by Rivolvan** [oysteinkrog/SQLite.Net-PCL#279]
I am having difficulty in saving custom types to SQLite database. Do I need to serialize the property? If so, how?
I am trying to save an object (with properties) to a column in the SQLite database with a TEXT data type in the form of a JSON format. Is there a way to convert the object automatically to JSON while using Insert, Update and Delete statements? I am using this in UWP and C#. Thank you!

**Comment by StefanFabian** [comment]
You could use a BlobSerializer.
Just make an instance of BlobSerializerDelegate and add a serialization routine i.e. converting the object to a string and the getting the bytes of the string and a deserialization the other way around bytes => string then specify the supported types and pass it to the SQLiteConnection constructor.

**Comment by seanfisher** [comment]
Thanks @StefanFabian for the suggestion. Here's the equivalent code. Suggestions are welcome.

    private SQLiteAsyncConnection CreateSqlConnection()
    {
        BlobSerializerDelegate.SerializeDelegate serializerDelegate = (obj) =>
        {
            return Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(obj));
        };
        BlobSerializerDelegate.DeserializeDelegate deserializerDelegate = (data, type) =>
        {
            using (var stream = new MemoryStream(data))
            {
                using (var reader = new StreamReader(stream, Encoding.UTF8))
                {
                    return JsonSerializer.Create().Deserialize(reader, type);
                }
            }
        };
        BlobSerializerDelegate.CanSerializeDelegate canDeserializeDelegate = (type) =>
        {
            return true;
        };
        var serializer = new BlobSerializerDelegate(
            serializerDelegate,
            deserializerDelegate,
            canDeserializeDelegate
        );
        return new SQLiteAsyncConnection(() => new SQLiteConnectionWithLock(Platform, new SQLiteConnectionString(GetDbPath(), true, serializer)));
    }

**Comment by Rivolvan** [comment]
thanks, but wouldn't that mean, every column will be serialized?

**Comment by seanfisher** [comment]
It's not serializing all columns for me, just complex types that it doesn't know how to handle already. I am using a database with tables that have already been created though - not sure if that matters. It could be that creating a table using this method would serialize everything.

If that's the case, it seems like you just have to change the `canDeserializeDelegate` to check against `type`. Something like this:

    BlobSerializerDelegate.CanSerializeDelegate canDeserializeDelegate = (type) =>
    {
        return
            !(type == typeof(int)) &&
            !(type == typeof(BigInteger)) &&
            !(type == typeof(bool)) &&
            !(type == typeof(Enum)) &&
            !(type == typeof(float)) &&
            !(type == typeof(string)) &&
            !(type == typeof(DateTime)) &&
            !(type == typeof(DateTimeOffset)) &&
            !(type == typeof(byte[])) &&
            !(type == typeof(Guid))
            ;
    }

I took the list of supported types from [praeclarum's wiki](https://github.com/praeclarum/sqlite-net/wiki/Features), which I assume is similar to the types this library supports. Please let me know how it works for you if you decide to use it this `BlobSerializerDelegate` approach - there isn't much documentation in this area and I'm trying to get a handle on it out as well.

**Comment by Rivolvan** [comment]
Thank you for the code. :) That's the missing piece.
