### ISSUE TITLE
Alternative for obsolete SQLiteConnectionPool?

### ISSUE THREAD

**Issue by pauldendulk** [oysteinkrog/SQLite.Net-PCL#281]
SQLiteConnectionPool is obsolete now. Is there an alternative in the library? Should we implement one ourselves? Or do you advise to not work with connection pools at all for common scenarios (I am not sure we need one)?

**Comment by oysteinkrog** [comment]
I am of the opinion that it is not really needed.

**Comment by pauldendulk** [comment]
fine, thanks for the quick response.

**Comment by HppZ** [comment]
why it is not needed? what is the best practice?
