### ISSUE TITLE
Can't Select property from a Table<T>() without ToList()ing it first

### ISSUE THREAD

**Issue by kodeo** [oysteinkrog/SQLite.Net-PCL#284]
This is a duplicate of an issue raised on sqlite-net which has gone unacknowledged for six weeks. I'm trying an upgrade to SQLite.Net-PCL and notice it exhibits the same behaviour, i.e. table properties are not available via a select until evaluated by a ToList() or similar first, i.e.:

    db.Table<Foo>().ToList().Select(x => x.id).ToArray(); // returns [1, 2, 3, 4]
    db.Table<Foo>().Select(x => x.id).ToArray(); // returns [0, 0, 0, 0]

Can anyone shed any light on this? Thanks.

**Comment by kodeo** [comment]
Apologies, this issue applies to SQLite-net PCL, not SQLite.Net PCL.

**Comment by oysteinkrog** [comment]
Good to hear, thanks for updating :)
