### ISSUE TITLE
SQLite.NET-PCL nuget should take dependency on VC Libs

### ISSUE THREAD

**Issue by srdjanjovcic** [oysteinkrog/SQLite.Net-PCL#292]
If you create a UWP app in managed language (e.g., C#) and add SQLLite nuget to it, it will crash on runtime because sqlite3.dll cannot be loaded. 

Workaround is to add "Visual C++ 2015 Runtime for Universal Windows Platform Apps" reference to the UWP app, alongside with SQLite.NET-PCL.

**Comment by StefanFabian** [comment]
Well actually you need the SQLite for Universal Windows extension(?) which should add the VC++ Runtime.

**Comment by srdjanjovcic** [comment]
I see, extensions does not add VCLibs, you just get warning:

_The SDK "SQLite.UWP.2015, Version=3.12.2" depends on the following SDK(s) "Microsoft.VCLibs, version=14.0", which have not been added to the project or were not found. Please ensure that you add these dependencies to your project or you may experience runtime issues. You can add dependencies to your project through the Reference Manager._
