### ISSUE TITLE
When is it planned to make a new version of the NuGet packages?

### ISSUE THREAD

**Issue by Reza1024** [oysteinkrog/SQLite.Net-PCL#304]
@oysteinkrog: The latest SQLite.NET-PCL package release was on last November. Is there any current plan as for when the new release would happen? I am especially interested in WinSQLite3 support in SQLite.Net.Platform.WinRT. Thanks

**Comment by digimezzo** [comment]
I confirm. There are some important fixes confirming queries with special characters which I'm interested in. The Nuget version is unusable for my specific case. The latest code on Github works like a charm.

**Comment by RezaJooyandeh** [comment]
It seems that this fork is not active anymore.
