### ISSUE TITLE
Add strong name to all assemblies

### ISSUE THREAD

**Issue by Centurys** [oysteinkrog/SQLite.Net-PCL#31]
Assembly generation failed -- Referenced assembly 'SQLite.Net' does not have a strong name

Add some e.g ".snk" keys to project and compile assemblies with strong name, to avoid error above.

**Comment by robv8r** [comment]
You wouldn't need to distribute two versions (one with a strong name and one without).  You'd only distribute the assembly with the strong name.  Having a strong name doesn't alienate anyone.

NOT having a strong name alienates those of us who do give our assemblies strong names.  Simply put: **a assembly with a strong name cannot take a dependency on an assembly that lacks a strong name.**

IMHO, in today's world of .Net, giving an assembly a strong name provides an additional level of security.  If a server is compromised, an assembly without a strong name could be decompiled, modified, and recompiled.  The existing assembly could then be replaced with the "modified" assembly.  If any malicious code is woven into the "modified" assembly, it would execute as though it had always been there.

If the assembly has a strong name, the CLR will refuse to load the assembly if the assembly has been tampered with.

You are correct that Nivot.StrongNaming (among others) provides users with a means of disassembling, strongly naming, then reassembling your NuGet package.  It's not very straightforward, and (to my knowledge) cannot be done at compile time.  This makes taking a dependency on the NuGet package more difficult for those of us who create strongly named assemblies.
