### ISSUE TITLE
nuget package not packaged correctly. net4 and net40 folders should be the same

### ISSUE THREAD

**Issue by JKennedy24** [oysteinkrog/SQLite.Net-PCL#310]
I have been looking at the Sqlite.Net-PCL and trying to reference it in my unit test project. I used to reference this project: https://www.nuget.org/packages/SQLite.Net.Platform.Win32/ but this has been unlisted.
This library is now in the net4 folder of this package. but my unit test project doesnt look at this folder it looks at the net40 folder. From this question on StackOverflow: http://stackoverflow.com/q/37724879/2987066. this may be a mistake.

**Comment by enantiomer2000** [comment]
I also am experiencing this issue.

**Comment by JKennedy24** [comment]
I don't know enough about Github or Nuget to fix this error but I know the error is in line 50 and 53 of this file:
https://github.com/oysteinkrog/SQLite.Net-PCL/blob/master/nuget/SQLite.Net.nuspec


line 50 should be:

        <file src="SQLite.Net.Platform.Win32\SQLite.Net.Platform.Win32.dll" target="lib\net40\SQLite.Net.Platform.Win32.dll" />

I'm not even sure what the SQLite.Net.Platform.Generic.dll file is or where it is needed

**Comment by EmilAlipiev** [comment]
addin system.data.sqlite package is workaround for this but I hope that it will be fixed in next release.

**Comment by JKennedy24** [comment]
closing as this project is dead
