### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by der-Daniel** [oysteinkrog/SQLite.Net-PCL#331]
Hi, 

I get a weird Error:
`{"near \"\n\": syntax error"}` 

But the query seems to be perfectly fine. I also tested it in SQLiteBrowser.
Copied from the Exception Break, the query is this:

```
create table if not exists "subscriptions"(
"Id" integer primary key autoincrement not null ,
"Name" varchar not null ,
"Url" varchar not null ,
"LastSync" bigint ,
"WebsiteUrl" varchar )
```

The following method is called:
`CreateTable<Subscription>();`

And my Class looks like this:

```
[Table("subscriptions")]
public class Subscription
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }
    [NotNull]
    public string Name { get; set; }
    [NotNull]
    public string Url { get; set; }
    public DateTime LastSync { get; set; }
    public string WebsiteUrl { get; set; }

}
```

I am creating a Windows 10 Universal App.

**Comment by der-Daniel** [comment]
Selectin is also not working:

query:
`select * from "subscriptions"`

error:
`{"unrecognized token: \"\"\""}`

**Comment by JonasR-** [comment]
Did you made any progress on this? got a similar problem

**Comment by der-Daniel** [comment]
No, I have ditched the project by now.
