### ISSUE TITLE
SqlitePlatformAndroid crashes in android widget

### ISSUE THREAD

**Issue by gautambjain** [oysteinkrog/SQLite.Net-PCL#346]
Please guide me. 

I am writing a android widget using Xamarin.

The widget crashes whenever I do `new SQLitePlatformAndroid()`. Meaning the constructor crashes. The same works in my Xamarin Android app and also Xamarin Forms.

What am I doing wrong?

**Comment by Immons** [comment]
https://developer.xamarin.com/releases/android/xamarin.android_7/xamarin.android_7.2/


Native Library Use

> Due to a change by Google, Android N will now only permit linking to NDK-provided native libraries. libsqlite.so is not an NDK-provided native library. Consequently, existing apps using e.g. Mono.Data.Sqlite.dll will crash when running on Android N. This may include other SQLite-using assemblies, not distributed with Xamarin.Android.
> 
> Xamarin.Android 7.0, which is part of Cycle 8, updates Mono.Data.Sqlite.dll to include a custom built version of libsqlite.so, named libsqlite3_xamarin.so.
> 
> All Developers need to audit their code for P/Invoke and ensure that referenced native libraries are either included in the Android NDK, or are included within the app.apk itself. The only Xamarin.Android-provided assembly impacted by this change is Mono.Data.Sqlite.dll.
