### ISSUE TITLE
Question: Setting Serialized Mode in PCL

### ISSUE THREAD

**Issue by sudmanche** [oysteinkrog/SQLite.Net-PCL#35]
Hi, in non PCL version of SQLite.Net I was able to do this for Android and iOS:

```
        SQLite.SQLite3.Shutdown();
        SQLite.SQLite3.Config(SQLite.SQLite3.ConfigOption.Serialized);
        SQLite.SQLite3.Initialize();
```

and this would stop the threading error.

I cannot see how to set serailize mode with the PCL. Can you explain please.

**Comment by squarepegg** [comment]
Is this still supported?
