### ISSUE TITLE
So, this project ended???

### ISSUE THREAD

**Issue by hupo376787** [oysteinkrog/SQLite.Net-PCL#370]
So, this project ended???

**Comment by oysteinkrog** [comment]
Yes, pretty much

**Comment by hupo376787** [comment]
Hm.....
This is the best project on UWP, we want it updated :sob:

**Comment by gautambjain** [comment]
I suggest that you try Sqlite-Net-PCL - https://github.com/praeclarum/sqlite-net

I successfully migrated to that project without much changes. Also it is being maintained actively. Performance also is lot better.

Thanks.

**Comment by hupo376787** [comment]
@gautambjain Thank you very much, I will look into it.

**Comment by developMediaSoft** [comment]
@oysteinkrog Could you please suggest how to migrate ISQLitePlatform's concrete, platform-specific implementations?
EDIT: I just removed it like I did most of the other things (besides constraining our generic types to new() instead of just class, now I need to take care of nullable Guids
