### ISSUE TITLE
How can I retrieve a single column value from a table?

### ISSUE THREAD

**Issue by WattsC-90** [oysteinkrog/SQLite.Net-PCL#381]
I need to retrieve a list of primary keys from the database/table.

I have tried using the Query<int>() method, but will only accept reference types as type arguments.. Is there an easy way to retrieve a single column value? I don't want to have to retrieve a list of objects from the table to then loop over them to extract a list of IDs, its long winded, CPU intensive for large data sets and seems unnecessary.

Any pointers/help here?

**Comment by kolinkor** [comment]
You can create view for your query, like:
` public class IdView
    {
        public string Id { get; set; }
    }
`
And then write query, like:
`private string _idQuery = 
@"Select Entities.Id as Id
From Entities";`
And finally call:
`List<IdView> = Connection.Query<IdView> (_idQuery );`

**Comment by WattsC-90** [comment]
Thanks! 
That is what i eventually did, it just seemed a bit mad to create an entirely new object to query this when the functionality seems so close.. and yet so far away!

Thanks for confirming my implementation!
