### ISSUE TITLE
Win32 parameter handling doesn't work

### ISSUE THREAD

**Issue by prasannavl** [oysteinkrog/SQLite.Net-PCL#41]
> {SQLite.Net.SQLiteException: near "?": syntax error
>  at SQLite.Net.Platform.Win32.SQLiteApiWin32.Prepare2(IDbHandle db, String query)}

is thrown every-time you use parameter binding. 
Same issue persists with named parameter.

My guess:
```C#
        private IDbStatement Prepare()
        {
            IDbStatement stmt = _sqlitePlatform.SQLiteApi.Prepare2(_conn.Handle, CommandText);
            BindAll(stmt);
            return stmt;
        }
```
BindAll is called after the IDbStatement, while the IDbStatement creation throws the error in Win32.

**Comment by raV720** [comment]
I have run across the same problem. Simple code that throws the same exception:

```
            var command = Database.CreateCommand("SELECT EXISTS(SELECT 1 FROM @Table WHERE @Column = @Value LIMIT 1)");

            command.Bind("@Table", mapping.TableName);
            command.Bind("@Column", mapping.PK.Name);
            command.Bind("@Value", pk);

            var result = command.ExecuteScalar<object>();
```
