### ISSUE TITLE
Bug: can't use NuGet for Xamarin Studio 5.4 environment

### ISSUE THREAD

**Issue by IlyaTsilikov** [oysteinkrog/SQLite.Net-PCL#57]
I've tryed to use SQLite.Net.Platform.XamarinIOS NuGet with a newest version of Xamarin.iOS (that's Xamarin Studio 5.4 environment and supports iOS 8 development) but got an error that my iOS class library isn't comaptible with the NuGet. I can guess the reason: the NuGet looks for MonoTouch assembly and don't find it 'cause currently this assembly has a name Xamarin.iOS. I'd like to know about plans to fix this bug.

**Comment by oysteinkrog** [comment]
This should be fixed with the new unified ios platform implementation.
