### ISSUE TITLE
Using SQLite-Net-PCL in Universal App

### ISSUE THREAD

**Issue by piotrek1231** [oysteinkrog/SQLite.Net-PCL#70]
Hi, 
I want to use SQLite-Net-PCL in Universal App. Few day ago I could create connection using: _sqlLiteConnection = new SQLiteConnection(_pathOfDatabase); , but after install this extension https://bitbucket.org/twincoders/sqlite-net-extensions SQLiteConnection expected from me SQLitePlatform. I have two problems connected with this issue: 

The first: 
When I install "SQLite.Net.Platform.WindowsPhone8" I still get "Install-Package : Could not install package 'sqlite-net-wp8 3.8.5'. You are trying 
to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1',
 but the package does not contain any assembly references or content files that are
 compatible with that framework. For more information, contact the package author."

The second: 
I save database in roaming data and initialize connection in Shared code. So, if I set platform as "WindowsPhone", I can't use this code in Windows App ? 

Thanks

**Comment by robhogfeldt** [comment]
Im interested in understanding how you got it to work. Im creating a universal app (win8.1 and WP8.1).
For the Win8.1 project I added a reference to SqLite.Net.Platform.WinRT.  
From what I can understand I could now manually download the files from:
https://github.com/oysteinkrog/SQLite.Net-PCL/tree/master/src/SQLite.Net.Platform.WinRT
and put them in my WP8.1-project. 
  Would it be possible for someone of you to put together a small guide maybe on how to do this? I get loads of errors from the SQLiteAPI when trying. Thanks!

**Comment by robhogfeldt** [comment]
Glad to see its possible to get it to work with WP8.1. 
Is it possible for someone here to write a small guide of how to use the Win8.1 version of the files in the WP8.1-project. I tried to simply copy the .cs-files from:
https://github.com/oysteinkrog/SQLite.Net-PCL/tree/master/src/SQLite.Net.Platform.WinRT

But I get a lot of errors in the SQLiteApiWinRT.cs. 
Should I maybe use the SQLite.Net.Platform.WinRT.csproj somehow?
Thank you

**Comment by dbeattie71** [comment]
Build the SQLite.Net, SQLiteAsync.Net, and the SQLite.Net.Platform.WindowsPhoneApp81 projects.  Add references to those in your WP81 project.

**Comment by robhogfeldt** [comment]
Thank you! 

All the references are now in place.
It did also cause the following missmatch if you happen to know a slotuion for this:
(This happens when I try to debug the app on my phone.)

"There was a mismatch between the processor architecture of the project being built "ARM" and the processor architecture of the reference "SQLite.Net.Platform.WindowsPhoneApp81", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project"

**Comment by dbeattie71** [comment]
I built in release, the PCL projects are set to Any CPU and the WindowPhone8 project is set to x86.

**Comment by robhogfeldt** [comment]
Thanks you for taking the time to help.
I know have the ARM-reference installed but there are still two references missing.
Sqlite3DatabaseHandle and  Sqlite3Statement. Are there references I can add in a similar way to solve this? Thanks again.

**Comment by robhogfeldt** [comment]
Thank you dbeattie71, it works!

**Comment by oysteinkrog** [comment]
I'm wondering if a nuget package that distributed the WindowsPhoneApp81 dll (and required the VS sqlite component) would work.
I assume that you guys do have the sqlite component installed in the app project? (I have 0 experience with WP development).

**Comment by apjones6** [comment]
Hey, I'm not very experienced with NuGet so I may be missing something, but I don't see why it wouldn't work. I've built the WindowsPhoneApp81 project into a package which I'm using for my universal phone project. It's working in both x86 on the emulator, and ARM on my physical device.

I used the .targets approach outlined at the end of this article: http://blogs.msdn.com/b/mim/archive/2013/09/02/packaging-a-windows-store-apps-component-with-nuget-part-2.aspx

I've included the nupkg file in my repository (and reference that folder as a package source so it restores from there): https://github.com/apjones6/RPGM/tree/develop/package-source

**Comment by oysteinkrog** [comment]
Please check if the latest version of the WinRT nuget works on WP 8.1

**Comment by apjones6** [comment]
Works for me in all scenarios perfectly; thank's for this!

I've tested in:
 - Visual Studio Emulator (VS 2013 WVGA 4 inch 512MB x86)
 - Debug my WP 8.1 (Nokia Lumia 620)
 - Deploy in release to same

I'm fairly sure I haven't anything in my project leftover from my above solution which would give false positives testing v2.5.1 (I checked the targets were removed from .csproj).

**Comment by oysteinkrog** [comment]
Don't thank me, thank @rmaclean :)
