### ISSUE TITLE
No ability to specify relational constraints against string columns

### ISSUE THREAD

**Issue by kentcb** [oysteinkrog/SQLite.Net-PCL#73]
Because `System.String` does not define operators `<`, `>`, `<=`, or `>=`, it is not possible to define a constraint such as:

```
conn.Table<FooDTO>()
    .Where(x => x.Name > "abc")
```

This may seem contrived, but this is critical to being able to correctly page through data per [the SQLite recommendations](http://www.sqlite.org/cvstrac/wiki?p=ScrollingCursor).

In my fork I plan on adding some extension methods to `string` such as `GreaterThan` and `LessThanOrEqual`, and then checking for invocations against those extension methods in addition to the existing checks against the operators. It's not exactly elegant, but I can't think of a better way to handle this right now.

**Comment by oysteinkrog** [comment]
I think your solution is a decent workaround.
