### ISSUE TITLE
SQLite for Windows Runtime (Windows 8.1)

### ISSUE THREAD

**Issue by StefanFabian** [oysteinkrog/SQLite.Net-PCL#84]
Hey,
the SQLite.Net.Platform.WinRT package installs an old version of the above mentioned extension.
So I'd like to ask if there's a reason for that / if it is save to update to the current version.

Version installed: 3.8.4.1
Current version:  3.8.7.2

**Comment by StefanFabian** [comment]
Since you updated the nugets I'd like to know if it works now with the current version 3.8.7.4 of SQLite for Windows Runtime

**Comment by oysteinkrog** [comment]
Hmm, this was probably not intentional, it's just that nobody is maintaining that code.
I've just merged a PR that removes that dep entirely, which I think should fix it.
