### ISSUE TITLE
NuGet package for Xamarin.iOS

### ISSUE THREAD

**Issue by lorddarkangel** [oysteinkrog/SQLite.Net-PCL#96]
Your package for monotouch works perfectyl. But we would need a NuGet package for Xamarion.iOS! Can you build it?

**Comment by hutjepower** [comment]
The latest version of this repository works like a charm btw. Both for Xamarin.IOS Classic and Unified API. In this issue (https://github.com/oysteinkrog/SQLite.Net-PCL/issues/100) oysteinkrog indicates a nuget package update to be released soon after his Christmas vacation. Up to now I would suggest to build your own reference...

**Comment by oysteinkrog** [comment]
I've pushed new nuget packages now, let me know if there are any problems:)
