### ISSUE TITLE
Updated nuget for Windows Phone 8.1

### ISSUE THREAD

**Issue by ravensorb** [oysteinkrog/SQLite.Net-PCL#98]
Any chance of an updated nuget package for Windows Phone 8.1 in the near future?

**Comment by oysteinkrog** [comment]
Unfortunately I don't have very much free time to work on this project, so I can't promise that I will find the time to work on that :/
If anyone wants to give it a try it would be very nice:)

**Comment by oysteinkrog** [comment]
Please check if the latest version of the WinRT nuget works on WP 8.1
